package com.mycompany.servermail;
// Generated 28.Eki.2015 12:57:22 by Hibernate Tools 4.3.1



/**
 * Messages generated by hbm2java
 */
public class Messages  implements java.io.Serializable {


     private Integer idMessage;
     private Integer sending;
     private String message;

    public Messages() {
    }

    public Messages(Integer sending, String message) {
       this.sending = sending;
       this.message = message;
    }
   
    public Integer getIdMessage() {
        return this.idMessage;
    }
    
    public void setIdMessage(Integer idMessage) {
        this.idMessage = idMessage;
    }
    public Integer getSending() {
        return this.sending;
    }
    
    public void setSending(Integer sending) {
        this.sending = sending;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }




}


