package com.mycompany.servermail;
// Generated 28.Eki.2015 12:57:22 by Hibernate Tools 4.3.1

import Util.HibernateUtil;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import org.hibernate.Session;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;




/**
 * Server generated by hbm2java
 */
public class Server  implements java.io.Serializable {


     public Integer idServer;
     private String from;
     private String password;
     private String to;
     private String content;
     private String port;
     private String server;

    public Server() {
    }

    public Server(String from, String password, String to, String content, String port, String server) {
       this.from = from;
       this.password = password;
       this.to = to;
       this.content = content;
       this.port = port;
       this.server = server;
    }
   
    public Integer getIdServer() {
        return this.idServer;
    }
    
    public void setIdServer(Integer idServer) {
        this.idServer = idServer;
    }
    public String getFrom() {
        return this.from;
    }
    
    public void setFrom(String from) {
        this.from = from;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTo() {
        return this.to;
    }
    
    public void setTo(String to) {
        this.to = to;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getPort() {
        return this.port;
    }
    
    public void setPort(String port) {
        this.port = port;
    }
    public String getServer() {
        return this.server;
    }
    
    public void setServer(String server) {
        this.server = server;
    }

}


